[scrub.schedule]
cron = "15 3 * * 3"

[status.schedule]
cron = "*/15 * * * *"
repeat_after = "24h"

[email]
from = "testfrom@test.com"
to = "test@test.com"
host = "test.host.com"
port = 587
username = "test"
password = "test"
